#pragma once
#include "ember/vulkan.hpp"
#include <cstdint>
#include <stdexcept>
#include <string>
#include <vector>

#define VK_CHECK(expr)                                                    \
    do {                                                                  \
        const VkResult _ember_vk_result = (expr);                         \
        if (_ember_vk_result != VK_SUCCESS)                              \
            throw std::runtime_error(std::string("ember/vulkan: ") +      \
                #expr " failed (" + std::to_string(_ember_vk_result) + ")"); \
    } while (0)

namespace ember::detail::vulkan {
// Frames in flight for the owned submission loop (WO-04); the skeleton keeps
// the constant so later stages share the value.
inline constexpr std::uint32_t kFramesInFlight = 2;
inline constexpr std::uint32_t kSimGroupSize = 64;
inline constexpr std::uint32_t kMaxSpawnRequests = maxSpawnRequests;
// Five public counters are copied back each frame (alive, deadHead, requests,
// capacity, allocated); the shader's counter block is eight words.
inline constexpr std::uint32_t kCounterWords = 8;
// Schedule storage holds metadata plus 512 three-word tiled sort commands
// (same bound as the GL backend: 2^30 capacity needs 276 commands).
inline constexpr std::uint64_t kScheduleBytes = (5 + 3 * 512) * sizeof(std::uint32_t);
// Event sub-emission (WO-08): GpuEvent is 48 B in std430; the queue is a
// 16-byte header followed by the fixed instance table.
inline constexpr std::uint32_t kMaxEventInstances = maxEventInstancesPerFrame;
inline constexpr std::uint32_t kMaxEventChildren = maxEventChildrenPerFrame;
inline constexpr std::uint64_t kGpuEventBytes = 48;
inline constexpr std::uint64_t kEventQueueBytes = 4ull * sizeof(std::uint32_t) + (std::uint64_t)kMaxEventInstances * kGpuEventBytes;
// Asynchronous statistics ring: one sample per update, bounded like the GL
// backend (4 slots; excess samples are dropped, never block simulation).
inline constexpr std::uint32_t kStatisticsSlots = 4;

// Descriptor bindings mirror the GL backend numbering on purpose: the shaders
// are shared SPIR-V, so the single Vulkan descriptor set uses the same slots.
// SSBO 0-13, UBO 14-19 (see docs/backends.md "Vulkan 渲染环境注入").
inline constexpr std::uint32_t kBindingCur = 0;
inline constexpr std::uint32_t kBindingNext = 1;
inline constexpr std::uint32_t kBindingSpawn = 2;
inline constexpr std::uint32_t kBindingDead = 3;
inline constexpr std::uint32_t kBindingCounters = 4;
inline constexpr std::uint32_t kBindingAttractors = 5;
inline constexpr std::uint32_t kBindingVortexes = 6;
inline constexpr std::uint32_t kBindingSprings = 7;
inline constexpr std::uint32_t kBindingSorted = 8;
inline constexpr std::uint32_t kBindingPalette = 9;
inline constexpr std::uint32_t kBindingIndirect = 10;
inline constexpr std::uint32_t kBindingLive = 11;
inline constexpr std::uint32_t kBindingScratch = 12;
inline constexpr std::uint32_t kBindingSchedule = 13;
// Event sub-emission (WO-08): per-slot metadata (uvec2: event tag + birth id),
// templates and the GPU event queue.
inline constexpr std::uint32_t kBindingEventTags = 20;      // uvec2 per particle slot
inline constexpr std::uint32_t kBindingEventTemplates = 21; // SpawnRequest[maxEventTemplates]
inline constexpr std::uint32_t kBindingEventQueue = 22;     // header + GpuEvent[maxEventInstancesPerFrame]
inline constexpr std::uint32_t kBindingUboSim = 14;
inline constexpr std::uint32_t kBindingUboSort = 15;
inline constexpr std::uint32_t kBindingUboSchedule = 16;
inline constexpr std::uint32_t kBindingUboDraw = 17;
inline constexpr std::uint32_t kBindingUboFrag = 18;
inline constexpr std::uint32_t kBindingUboBloom = 19;

inline bool isDepthFormat(VkFormat f) {
    switch (f) {
        case VK_FORMAT_D16_UNORM:
        case VK_FORMAT_D32_SFLOAT:
        case VK_FORMAT_D24_UNORM_S8_UINT:
        case VK_FORMAT_D32_SFLOAT_S8_UINT:
            return true;
        default:
            return false;
    }
}

inline std::uint32_t nextPow2(std::uint32_t v) {
    if (v <= 1) return 1;
    v--;
    v |= v >> 1; v |= v >> 2; v |= v >> 4; v |= v >> 8; v |= v >> 16;
    return v + 1;
}

// Embedded fallback blobs generated by tools/embed_spirv.py at build time.
struct SpirvBlob {
    const unsigned char* data = nullptr;
    std::size_t size = 0;
    bool valid() const { return data && size; }
};
SpirvBlob embeddedSpirv(const char* name);

// Owned VkBuffer + VkDeviceMemory pair. No VMA: the backend allocates one
// memory object per resource, which is fine for the fixed resource set here.
struct Buffer {
    VkBuffer buffer = VK_NULL_HANDLE;
    VkDeviceMemory memory = VK_NULL_HANDLE;
    VkDeviceSize size = 0;
    void* mapped = nullptr; // non-null for persistently mapped host-visible
    bool valid() const { return buffer != VK_NULL_HANDLE; }
};

// Cached physical-device limits used by validateConfiguration.
struct DeviceLimits {
    std::uint64_t maxStorageBufferRange = 0;
    std::uint32_t maxComputeWorkGroupCountX = 0;
    VkDeviceSize minStorageBufferOffsetAlignment = 1;
    bool valid = false;
};
} // namespace ember::detail::vulkan
