#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Embed build-time SPIR-V binaries into a C++ translation unit.

The Vulkan backend prefers editable <shaderDir>/<name>.spv files and falls
back to these blobs when no file is present — the same "files first, embedded
copy as fallback" strategy the GL backend uses for GLSL. SPIR-V is a build
product, so the generated .cpp lives in the build tree, never the source tree.

Usage: embed_spirv.py <spirv_dir> <out.cpp>
"""
import pathlib
import sys

# Keep in sync with the _ember_spv_shaders list in CMakeLists.txt.
SHADERS = [
    "simulate.comp",
    "sort.comp",
    "schedule.comp",
    "particle.vert",
    "particle.frag",
    "bloom.vert",
    "bloom_threshold.frag",
    "bloom_blur.frag",
    "bloom_composite.frag",
]


def emit(out, name, data):
    symbol = name.replace(".", "_")
    # alignas(4): VkShaderModuleCreateInfo::pCode must be 4-byte aligned.
    out.write("alignas(4) const unsigned char kSpirv_%s[] = {%s};\n" % (
        symbol, ",".join(str(b) for b in data)))
    out.write("const std::size_t kSpirv_%s_size = sizeof(kSpirv_%s);\n\n" % (symbol, symbol))


def main():
    if len(sys.argv) != 3:
        print("usage: embed_spirv.py <spirv_dir> <out.cpp>", file=sys.stderr)
        return 2
    spirv_dir = pathlib.Path(sys.argv[1])
    out_path = pathlib.Path(sys.argv[2])

    chunks = []
    for name in SHADERS:
        path = spirv_dir / (name + ".spv")
        if not path.is_file():
            print("ERROR: missing SPIR-V %s" % path, file=sys.stderr)
            return 1
        chunks.append((name, path.read_bytes()))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// Generated by tools/embed_spirv.py — do not edit.\n")
        out.write('#include "common.hpp"\n')
        out.write("#include <cstring>\n\n")
        out.write("namespace ember::detail::vulkan {\n\n")
        for name, data in chunks:
            emit(out, name, data)
        out.write("SpirvBlob embeddedSpirv(const char* name) {\n")
        out.write("    if (!name) return {};\n")
        for name, _ in chunks:
            symbol = name.replace(".", "_")
            out.write('    if (std::strcmp(name, "%s") == 0) return {kSpirv_%s, kSpirv_%s_size};\n'
                      % (name, symbol, symbol))
        out.write("    return {};\n}\n\n")
        out.write("} // namespace ember::detail::vulkan\n")
    print("embedded %d SPIR-V modules -> %s" % (len(chunks), out_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
